cleanup(OWNERS): remove inactive approvers
falcosecurity/plugin-sdk-go pull request #58
Opened 2022-07-05 15:15 UTC by jasondellaluce

**What type of PR is this?**

/kind cleanup

/kind documentation

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

For https://github.com/falcosecurity/falco/issues/2115, this PR moves inactive approvers (who had very little or zero contributions over the past 6 months) from `approvers` to `emeritus_approvers` in OWNERS.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-07-05 15:15 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/plugin-sdk-go/pull/58#" title="Author self-approved">jasondellaluce</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fplugin-sdk-go).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/plugin-sdk-go/blob/main/OWNERS)~~ [jasondellaluce]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-07-06 10:34 UTC, fntlnz requested changes
Please restore `fntlnz` https://github.com/falcosecurity/falco/issues/2115#issuecomment-1176045086

2022-07-14 09:13 UTC, jasondellaluce commented
@fntlnz, given https://github.com/falcosecurity/falco/issues/2122 I understand that you'd like to step down as maintainer of this repository too.

Can you please remove your Change Request here or sign-off your commit on #61 to unblock the DCO there?

Of the two, I would prefer proceeding with this one that puts your name under the `emeritus_approvers` section, let me know what you think.

2022-07-18 14:45 UTC, jasondellaluce commented
Closing this in favor of #64.

/close

2022-07-18 14:45 UTC, poiana commented
@jasondellaluce: Closed this PR.

<details>

In response to [this](https://github.com/falcosecurity/plugin-sdk-go/pull/58#issuecomment-1187591741):

>Closing this in favor of #64.
>
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-07-18 14:45 UTC, closed without merging